name: Bug Report
description: Report a bug in Subterfuge. For feature requests or balance feedback, please use Discord.
title: "[Bug]: "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting a bug!

        **Important:** This form is for **bug reports only**. For feature requests, balance feedback, or general discussion, please visit our [Discord](https://discord.gg/TGZ2kFTDQV).

        Please fill out all required fields to help us investigate the issue.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you playing on?
      options:
        - iOS
        - Android
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Information
      description: Make and model of your device
      placeholder: "e.g., iPhone 14 Pro, Samsung Galaxy S23"
    validations:
      required: true

  - type: input
    id: player-name
    attributes:
      label: Your In-Game Name
      description: Your name in the game. If playing an anonymous game, provide your color instead.
      placeholder: "e.g., Captain_Sub or Blue"
    validations:
      required: true

  - type: input
    id: game-version
    attributes:
      label: Game Version
      description: Small white number found on main screen
      placeholder: "e.g., 10999"
    validations:
      required: true

  - type: input
    id: game-name
    attributes:
      label: Name of Game
      description: The name of the game in the game list where this bug occurred
      placeholder: "e.g., Battle for Neptune"
    validations:
      required: true

  - type: textarea
    id: bug-details
    attributes:
      label: Bug Details
      description: Please fill out each section below
      value: |
        ## What happened?
        Describe the bug...

        ## Steps to reproduce
        1.
        2.
        3.

        ## What did you expect to happen?
        Describe expected behavior...

        ## Screenshots/Videos (REQUIRED)
        Drag and drop images or videos here. Bug reports without visual evidence may be closed.

        **How to record your screen:**
        - **iOS:** Go to Settings → Control Center → add "Screen Recording". Then swipe down from top-right corner and tap the record button.
        - **Android:** Swipe down from the top of the screen and tap "Screen Record" (may vary by device).
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmation
      description: Please confirm the following before submitting
      options:
        - label: This is a bug report, NOT a feature request or balance feedback (those go to Discord)
          required: true
        - label: I have searched existing issues to ensure this bug has not already been reported
          required: true
